=== ontology-tools/onto-spread-ed/onto_spread_ed/static/schema/release_script.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "definitions": {
    "release-step-name": {
      "type": "string",
      "enum": [
        "GITHUB_PUBLISH",
        "HUMAN_VERIFICATION",
        "IMPORT_EXTERNAL",
        "BUILD",
        "MERGE",
        "PREPARATION",
        "VALIDATION",
        "BCIO_SEARCH"
      ]
    },
    "file": {
      "type": "object",
      "properties": {
        "sources": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1
            },
            {
              "type": "array",
              "items": {
                "anyOf": [
                  {
                    "type": "string",
                    "minLength": 1
                  },
                  {
                    "type": "object",
                    "properties": {
                      "file": {
                        "type": "string"
                      },
                      "type": {
                        "type": "string",
                        "enum": [
                          "classes",
                          "individuals",
                          "relations",
                          "owl"
                        ]
                      }
                    },
                    "required": [
                      "file",
                      "type"
                    ]
                  }
                ]
              }
            }
          ]
        },
        "target": {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "file": {
                  "type": "string",
                  "minLength": 1
                },
                "iri": {
                  "type": "string",
                  "minLength": 1
                },
                "ontology_annotations": {
                  "type": "object",
                  "properties": {},
                  "additionalProperties": {
                    "type": "string",
                    "minLength": 1
                  }
                }
              },
              "required": [
                "file",
                "iri"
              ]
            },
            {
              "type": "string"
            }
          ]
        },
        "needs": {
          "type": "array",
          "minLength": 0,
          "items": {
            "type": "string",
            "minLength": 1
          }
        }
      },
      "required": [
        "sources",
        "target"
      ]
    }
  },
  "description": "Release script schema",
  "type": "object",
  "properties": {
    "external": {
      "$ref": "#/definitions/file"
    },
    "files": {
      "type": "object",
      "properties": {
      },
      "additionalProperties": {
        "$ref": "#/definitions/file"
      },
      "propertyNames": {
        "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
      }
    },
    "iri_prefix": {
      "type": "string",
      "minLength": 1
    },
    "prefixes": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      },
      "properties": {}
    },
    "short_repository_name": {
      "type": "string",
      "minLength": 1
    },
    "full_repository_name": {
      "type": "string",
      "minLength": 1
    },
    "steps": {
      "type": "array",
      "minLength": 1,
      "default": [
        "PREPARATION",
        "VALIDATION",
        "IMPORT_EXTERNAL",
        "BUILD",
        "MERGE",
        "HUMAN_VERIFICATION",
        "GITHUB_PUBLISH"
      ],
      "items": {
        "anyOf": [
          {
            "$ref": "#/definitions/release-step-name"
          },
          {
            "type": "object",
            "properties": {
              "name": {
                "$ref": "#/definitions/release-step-name"
              },
              "args": {
                "type": "object",
                "additionalProperties": true
              }
            }
          }
        ]
      }
    }
  },
  "required": [
    "external",
    "files",
    "iri_prefix",
    "short_repository_name",
    "full_repository_name",
    "steps"
  ],
  "additionalProperties": false
}

=== ontology-tools/onto-spread-ed/onto_spread_ed/static/gmho.release.json
{
  "$schema": "schema/release_script.json",
  "iri_prefix": "https://galenos.org.uk/ontologies/",
  "full_repository_name": "b-gehrke/mental-health-ontology",
  "short_repository_name": "GMHO",
  "prefixes": {
    "GMHO": "https://galenos.org.uk/ontologies/GMHO_"
  },
  "external": {
    "target": {
      "file": "UpperLevel/gmho_external.owl",
      "iri": "https://galenos.org.uk/ontologies/gmho_external.owl"
    },
    "sources": [
      "UpperLevel/GMHO_External_Imports.xlsx"
    ]
  },
  "files": {
    "setting": {
      "target": {
        "file": "setting.owl",
        "iri": "https://galenos.org.uk/ontologies/setting.owl"
      },
      "sources": [
        "Intervention setting/Intervention setting.xlsx"
      ],
      "needs": []
    },
    "cad": {
      "target": {
        "file": "cad.owl",
        "iri": "https://galenos.org.uk/ontologies/cad.owl"
      },
      "sources": [
        "Intervention content and delivery/Intervention content and delivery.xlsx"
      ],
      "needs": []
    },
    "cse": {
      "target": {
        "file": "cse.owl",
        "iri": "https://galenos.org.uk/ontologies/cse.owl"
      },
      "sources": [
        "Intervention outcomes and spillover effects/Intervention outcomes and spillover effects.xlsx"
      ],
      "needs": []
    },
    "methods": {
      "target": {
        "file": "methods.owl",
        "iri": "https://galenos.org.uk/ontologies/methods.owl"
      },
      "sources": [
        "Research methods/Research methods.xlsx"
      ],
      "needs": []
    },
    "population": {
      "target": {
        "file": "population.owl",
        "iri": "https://galenos.org.uk/ontologies/population.owl"
      },
      "sources": [
        "Intervention population/Intervention population.xlsx"
      ],
      "needs": []
    },
    "mapped": {
      "target": {
        "file": "mapped.owl",
        "iri": "https://galenos.org.uk/ontologies/mapped.owl"
      },
      "sources": [
        "Non-GMHO entities mapped to LSRs/Non-GMHO entities mapped to LSRs.xlsx"
      ],
      "needs": []
    },
    "moa": {
      "target": {
        "file": "moa.owl",
        "iri": "https://galenos.org.uk/ontologies/moa.owl"
      },
      "sources": [
        "Intervention mechanism/Intervention mechanism of action.xlsx"
      ],
      "needs": []
    },
    "gmho": {
      "target": {
        "file": "gmho.owl",
        "iri": "https://galenos.org.uk/ontologies/gmho.owl"
      },
      "needs": [],
      "sources": [
        "setting.owl",
        "cad.owl",
        "cse.owl",
        "methods.owl",
        "population.owl",
        "mapped.owl",
        "moa.owl"
      ]
    }
  },
  "steps": [
    "PREPARATION",
    "VALIDATION",
    "IMPORT_EXTERNAL",
    "BUILD",
    "MERGE",
    "HUMAN_VERIFICATION",
    "GITHUB_PUBLISH"
  ]
}

=== ontology-tools/onto-spread-ed/onto_spread_ed/static/bcio.release.json
{
  "$schema": "schema/release_script.json",
  "iri_prefix": "http://humanbehaviourchange.org/ontology/",
  "full_repository_name": "b-gehrke/ontologies",
  "short_repository_name": "BCIO",
  "prefixes": {
    "BCIOR": "http://humanbehaviourchange.org/ontology/BCIOR_",
    "BCIO": "http://humanbehaviourchange.org/ontology/BCIO_",
    "ADDICTO": "http://addictovocab.org/ADDICTO_"
  },
  "external": {
    "target": {
      "file": "Upper Level BCIO/bcio_external.owl",
      "iri": "http://humanbehaviourchange.org/ontology/bcio_external.owl"
    },
    "sources": [
      "Upper Level BCIO/inputs/BCIO_External_Imports.xlsx"
    ]
  },
  "files": {
    "upper": {
      "target": {
        "file": "Upper Level BCIO/bcio_upper_level.owl",
        "iri": "http://humanbehaviourchange.org/ontology/bcio_upper.owl"
      },
      "sources": [
        "Upper Level BCIO/inputs/BCIO_Upper_Defs.xlsx",
        {
          "type": "relations",
          "file": "Upper Level BCIO/inputs/BCIO_Upper_Rels.xlsx"
        }
      ]
    },
    "bcio_setting": {
      "sources": [
        "Setting/bcio_setting.xlsx"
      ],
      "target": "Setting/bcio_setting.owl",
      "needs": [
        "upper"
      ]
    },
    "bcio_mode_of_delivery": {
      "sources": [
        "ModeOfDelivery/bcio_mode_of_delivery.xlsx"
      ],
      "target": "ModeOfDelivery/bcio_mode_of_delivery.owl",
      "needs": [
        "upper"
      ]
    },
    "bcio_source": {
      "sources": [
        "Source/bcio_source.xlsx"
      ],
      "target": "Source/bcio_source.owl",
      "needs": [
        "upper"
      ]
    },
    "bcio_moa": {
      "sources": [
        "MechanismOfAction/bcio_moa.xlsx"
      ],
      "target": "MechanismOfAction/bcio_moa.owl",
      "needs": [
        "upper"
      ]
    },
    "bcio_behaviour": {
      "sources": [
        "Behaviour/bcio_behaviour.xlsx"
      ],
      "target": "Behaviour/bcio_behaviour.owl",
      "needs": [
        "upper"
      ]
    },
    "bcto": {
      "sources": [
        "BehaviourChangeTechniques/bcto.xlsx"
      ],
      "target": "BehaviourChangeTechniques/bcto.owl",
      "needs": [
        "upper"
      ]
    },
    "bcio_style": {
      "sources": [
        "StyleOfDelivery/bcio_style.xlsx"
      ],
      "target": "StyleOfDelivery/bcio_style.owl",
      "needs": [
        "upper"
      ]
    },
    "bcio": {
      "sources": [
        "Setting/bcio_setting.owl",
        "ModeOfDelivery/bcio_mode_of_delivery.owl",
        "Source/bcio_source.owl",
        "MechanismOfAction/bcio_moa.owl",
        "Behaviour/bcio_behaviour.owl",
        "BehaviourChangeTechniques/bcto.owl",
        "StyleOfDelivery/bcio_style.owl"
      ],
      "target": {
        "file": "Upper Level BCIO/bcio.owl",
        "iri": "http://humanbehaviourchange.org/ontology/bcio.owl",
        "ontology_annotations": {
          "rdfs:comment": "The Behaviour Change Intervention Ontology (BCIO) is an ontology for all aspects of human behaviour change interventions and their evaluation. It is being developed as a part of the Human Behaviour Change Project (http://www.humanbehaviourchange.org). The BCIO is developed across several modules. This ontology file contains the merged version of the BCIO, encompassing the upper level and the modules for Setting, Mode of Delivery, Style of Delivery, Source, Mechanisms of Action, Behaviour and Behaviour Change Techniques. Additional modules will be added soon.",
          "dc:title": "Behaviour Change Intervention Ontology"
        }
      }
    }
  },
  "steps": [
    "PREPARATION",
    "VALIDATION",
    "IMPORT_EXTERNAL",
    "BUILD",
    "MERGE",
    "HUMAN_VERIFICATION",
    {
      "name": "BCIO_SEARCH",
      "args": {
        "included_files": [
          "upper",
          "bcio_setting",
          "bcio_mode_of_delivery",
          "bcio_source",
          "bcio_moa",
          "bcio_behaviour",
          "bcto",
          "bcio_style"
        ]
      }
    },
    "GITHUB_PUBLISH"
  ]
}

=== ontology-tools/onto-spread-ed/ose/static/gmho.release.json
{
  "iri_prefix": "https://galenos.org.uk/ontologies/",
  "short_repository_name": "GMHO",
  "full_repository_name": "b-gehrke/mental-health-ontology",
  "external": {
    "sources": [
      {
        "file": "UpperLevel/GMHO_External_Imports.xlsx",
        "type": "classes"
      }
    ],
    "target": {
      "file": "UpperLevel/gmho_external.owl",
      "iri": "https://galenos.org.uk/ontologies/gmho_external.owl",
      "ontology_annotations": {}
    },
    "needs": []
  },
  "files": {
    "gmho": {
      "sources": [
        {
          "file": "Intervention setting/Intervention setting.xlsx",
          "type": "classes"
        },
        {
          "file": "Intervention content and delivery/Intervention content and delivery.xlsx",
          "type": "classes"
        },
        {
          "file": "Intervention outcomes and spillover effects/Intervention outcomes and spillover effects.xlsx",
          "type": "classes"
        },
        {
          "file": "Research methods/Research methods.xlsx",
          "type": "classes"
        },
        {
          "file": "Intervention population/Intervention population.xlsx",
          "type": "classes"
        },
        {
          "file": "Non-GMHO entities mapped to LSRs/Non-GMHO entities mapped to LSRs.xlsx",
          "type": "classes"
        },
        {
          "file": "Intervention mechanism/Intervention mechanism of action.xlsx",
          "type": "classes"
        },
        {
          "file": "Temporary entity spreadsheet/Temporary entity spreadsheet.xlsx",
          "type": "classes"
        }
      ],
      "target": {
        "file": "gmho_with_imports.owl",
        "iri": "https://galenos.org.uk/ontologies/gmho_with_imports.owl",
        "ontology_annotations": {},
        "publish": false
      },
      "needs": [
        "gmho_upper"
      ]
    },
    "gmho_final": {
      "sources": [
        {
          "file": "gmho_with_imports.owl",
          "type": "owl"
        },
        {
          "file": "gmho_upper.owl",
          "type": "owl"
        }
      ],
      "target": {
        "file": "gmho.owl",
        "iri": "https://galenos.org.uk/ontologies/gmho.owl",
        "ontology_annotations": {}
      },
      "needs": []
    },
    "gmho_upper": {
      "sources": [
        {
          "file": "UpperLevel/GMHO_Upper_Rels.xlsx",
          "type": "relations"
        },
        {
          "file": "UpperLevel/GMHO_Upper_Defs.xlsx",
          "type": "classes"
        }
      ],
      "target": {
        "file": "gmho_upper.owl",
        "iri": "https://galenos.org.uk/ontologies/gmho_upper.owl",
        "ontology_annotations": {}
      },
      "needs": []
    }
  },
  "steps": [
    {
      "name": "PREPARATION",
      "args": {}
    },
    {
      "name": "IMPORT_EXTERNAL",
      "args": {}
    },
    {
      "name": "VALIDATION",
      "args": {}
    },
    {
      "name": "BUILD",
      "args": {}
    },
    {
      "name": "MERGE",
      "args": {}
    },
    {
      "name": "HUMAN_VERIFICATION",
      "args": {}
    },
    {
      "name": "GITHUB_PUBLISH",
      "args": {}
    }
  ],
  "prefixes": {
    "ADDICTO": "http://addictovocab.org/ADDICTO_",
    "BCIO": "http://humanbehaviourchange.org/ontology/BCIO_",
    "EFO": "http://www.ebi.ac.uk/efo/EFO_",
    "GMHO": "https://galenos.org.uk/ontologies/GMHO_",
    "GMHOR": "https://galenos.org.uk/ontologies/GMHOR_"
  }
}

=== ontology-tools/onto-spread-ed/onto_spread_ed/static/addicto.release.json
{
  "$schema": "./schema/release_script.json",
  "iri_prefix": "http://addictovocab.org/ADDICTO_",
  "short_repository_name": "AddictO",
  "full_repository_name": "b-gehrke/addiction-ontology",
  "external": {
    "sources": [
      {
        "file": "imports/External_Imports.xlsx",
        "type": "classes"
      }
    ],
    "target": {
      "file": "addicto_external.owl",
      "iri": "http://addictovocab.org/addicto_external.owl",
      "ontology_annotations": {}
    },
    "needs": [],
    "renameTermFile": "imports/External_Imports_New_Labels.csv",
    "addParentsFile": "imports/External_Imports_New_Parents.csv"
  },
  "files": {
    "addicto": {
      "sources": [],
      "target": {
        "file": "addicto_with_imports.owl",
        "iri": "http://addictovocab.org/addicto_with_imports.owl",
        "ontology_annotations": {}
      },
      "needs": []
    },
    "addicto_final": {
      "sources": [
        {
          "file": "addicto_with_imports.owl",
          "type": "owl"
        }
      ],
      "target": {
        "file": "addicto.owl",
        "iri": "http://addictovocab.org/addicto.owl",
        "ontology_annotations": {
          "rdfs:comment": "The Addiction Ontology (AddictO) is an ontology being developed all aspects of addiction research."
        }
      },
      "needs": []
    }
  },
  "steps": [
    {
      "name": "PREPARATION",
      "args": {}
    },
    {
      "name": "VALIDATION",
      "args": {}
    },
    {
      "name": "IMPORT_EXTERNAL",
      "args": {}
    },
    {
      "name": "BUILD",
      "args": {}
    },
    {
      "name": "MERGE",
      "args": {}
    },
    {
      "name": "HUMAN_VERIFICATION",
      "args": {}
    },
    {
      "name": "GITHUB_PUBLISH",
      "args": {}
    }
  ],
  "prefixes": {
    "ADDICTO": "http://addictovocab.org/ADDICTO_",
    "BCIO": "http://humanbehaviourchange.org/ontology/BCIO_",
    "EFO": "http://www.ebi.ac.uk/efo/EFO_"
  }
}
